# %%
import sys
import os
from pathlib import Path
import pandas as pd
import zarr
import xarray as xr
import numpy as np

import shutil
from scipy.stats.mstats import plotting_positions
import time
from glob import glob
from tqdm import tqdm

import os
import sys

from pathlib import Path


cwd = Path.cwd()
while cwd.name != "stormy":
    cwd = cwd.parent
cwd = cwd / "flood_attribution"
# cwd = cwd / "local"
sys.path.insert(0, str(cwd))


from local.__inputs import (
    F_EXPERIMENT_DESIGN,
    DIR_FFA_SCRIPTS_LOCAL_OUTPUTS,
    PLOT_PARAMS,
)


from local.__inputs import (
    F_SIM_MULTIVAR_RETURN_PERIODS,
    F_BS_UNCERTAINTY_EVENTS_IN_CI,
    F_DESIGN_STORM_TSERIES_BASED_ON_SSR,
    F_TRITON_OUTPUTS_DSGN,
    F_SIM_FLOOD_PROBS_BOOTSTRAPPED,
    FPATH_ENSEMBLE_DESIGN_FLOODS,
    DIF_FFA_FLOOD_MAPPING,
    MIN_THRESH_FLDING,
    LST_KEY_FLOOD_THRESHOLDS,
    F_WSHED_SHP,
    EVENT_STAT_FOR_MC_DSGN_STRM_SEL_MULTIVAR_AND,
    FORMULATION_FOR_MC_DSGN_STRM_SEL_MULTIVAR_AND,
    FORMULATION_FOR_MC_DSGN_STRM_SEL_MULTIVAR_OR,
    EVENT_STAT_FOR_MC_DSGN_STRM_SEL_MULTIVAR_OR,
    FPATH_MC_DESIGN_FLOODS_MULTIVAR_AND,
    FPATH_MC_DESIGN_FLOODS_MULTIVAR_OR,
    FPATH_MC_DESIGN_FLOODS_UNIVAR,
    FORMULATION_FOR_MC_DSGN_STRM_SEL_UNIVAR,
    EVENT_STAT_FOR_MC_DSGN_STRM_SEL_UNIVAR,
    TARGET_DESIGN_STORM_DURATION_HRS_FOR_COMPARISON,
    LST_RTRNS,
    LST_FLOOD_DEPTH_BIN_EDGES,
    DIR_PLOTS_FLOOD_VS_EVENT_PROB,
    NUISANCE_THRESHOLD,
    MC_QUANTS_FOR_FLOOD_MAPPING,
    F_SIM_FLOOD_PROBS_BOOTSTRAPPED_CIS,
    F_RASTER_FEMA_100YR_DEPTHS
)

from local.__utils import (
    return_ds_sim_flood_probs,
    write_netcdf_of_ensemble_based_return_period_floods,
    return_ds_gridsize,
    analyze_baseline_flooded_area_vs_design_storm_flooded_areas,
    write_netcdf_of_mcds_return_period_floods,
    retrieve_event_statistic_return_periods_indexed_by_event_number,
    write_zarr,
    delete_zarr,
    retrieve_ssfha_bootstrapped_CIs,
    return_event_ids_for_each_ssfha_quantile,
)
from local.__plotting import (
    plot_flooded_areas_baseline_vs_alt,
    plot_triton_results,
    plot_histogram_of_differences_in_flood_depths_vs_baseline,
    plot_ensemble_vs_alternatives_probability_depth_curves_at_individual_gridcells,
    plot_event_statistic_return_period_scatterplots_for_target_return_period_and_minimum_flood_depth,
    plot_event_statistic_return_period_maps_for_target_return_period_and_minimum_flood_depth,
    tidy_hydro_varnames_for_plots,
    add_subplot_id,
)


clf = True
overwrite_outputs = False
prompt_for_rerun = False
plot_examples_of_flood_prob_curves = False


if not clf:
    print("not clearing plots which will slow down the script")
    print("############")
if overwrite_outputs:
    print(
        "overwrite_outputs is  set to True, so .zarr or .netcdf\n\
files generated by this script will be overwritten if they already exist"
    )
    print("############")
if not prompt_for_rerun and not overwrite_outputs:
    print(
        "prompt_for_rerun is set to False, meaning the user will not\n\
be asked to enter an input as to whether or not to re-write .zarr and .nc outputs."
    )
    print("############")
if not plot_examples_of_flood_prob_curves:
    print(
        "function to plot depth probability curve comparisons at sample\n\
locations is turned off"
    )
    print("############")
f_dsgn_tseries = F_DESIGN_STORM_TSERIES_BASED_ON_SSR
ds_dsgn_tseries = xr.open_dataset(f_dsgn_tseries)

ds_triton_dsgn = xr.open_dataset(F_TRITON_OUTPUTS_DSGN, engine="zarr").chunk("auto")


#  11/19/2025 work - making sure that design storm {event type = compound, sim type = rain-only} is the same as design storm {event type = rain, sim type = rain-only}
perform_comparison_of_rain_only_design_storms = False

if perform_comparison_of_rain_only_design_storms:
    for year in ds_triton_dsgn.year.to_series():
        for event_id in ds_triton_dsgn.event_id.to_series():
            ds_cmpnd_rainonly = ds_triton_dsgn["max_wlevel_m"].sel(
                event_type="compound",
                simtype="rainonly",
                model="tritonswmm",
                year=year,
                event_id=event_id,
            )
            tseries_cmpnd_rainonly = (
                ds_dsgn_tseries.sel(event_type="compound", year=year, event_id=event_id)
                .to_dataframe()
                .loc[:, ["mm_per_hr", "waterlevel_m"]]
            ).dropna()

            ds_rain_rainonly = ds_triton_dsgn["max_wlevel_m"].sel(
                event_type="rain",
                simtype="rainonly",
                model="tritonswmm",
                year=year,
                event_id=event_id,
            )
            tseries_rain_rainonly = (
                ds_dsgn_tseries.sel(event_type="rain", year=year, event_id=event_id)
                .to_dataframe()
                .loc[:, ["mm_per_hr", "waterlevel_m"]]
            ).dropna()

            ds_rain_cmpnd = ds_triton_dsgn["max_wlevel_m"].sel(
                event_type="rain",
                simtype="compound",
                model="tritonswmm",
                year=year,
                event_id=event_id,
            )
            tseries_rain_cmpnd = (
                ds_dsgn_tseries.sel(event_type="rain", year=year, event_id=event_id)
                .to_dataframe()
                .loc[:, ["mm_per_hr", "waterlevel_m"]]
            ).dropna()

            fig, axes = plt.subplots(3, 3, figsize=(16, 12))
            fig.suptitle(f"year = {year}, event_id = {event_id}")
            ax = axes[0, 0]
            ds_rain_cmpnd.where(ds_rain_cmpnd > 0).plot(x="x", y="y", ax=ax)
            ax.set_title("etype = rain, simtype = combined")
            ax.set_xlabel("")
            ax.set_ylabel("")
            ax.set_xticks([])
            ax.set_yticks([])
            ax = axes[0, 2]
            tseries_cmpnd_rainonly["waterlevel_m"].plot(ax=ax)
            tseries_cmpnd_rainonly["mm_per_hr"].plot(ax=ax, secondary_y=True)
            weather_index = tseries_cmpnd_rainonly[
                tseries_cmpnd_rainonly["mm_per_hr"] > 0
            ].index
            rain_dur_hr = (
                weather_index.max()
                - weather_index.min()
                + weather_index.diff().dropna()[0]
            ) / np.timedelta64(1, "h")
            ax.set_title(f"{rain_dur_hr} hr rainfall")
            ax.set_xlabel("")
            ax.set_ylabel("")

            ax = axes[1, 0]
            ds_rain_rainonly.where(ds_rain_rainonly > 0).plot(x="x", y="y", ax=ax)
            ax.set_title("etype = rain, simtype = rainonly")
            ax.set_xlabel("")
            ax.set_ylabel("")
            ax.set_xticks([])
            ax.set_yticks([])
            ax = axes[1, 2]
            tseries_rain_rainonly["waterlevel_m"].plot(ax=ax)
            tseries_rain_rainonly["mm_per_hr"].plot(ax=ax, secondary_y=True)
            weather_index = tseries_rain_rainonly[
                tseries_rain_rainonly["mm_per_hr"] > 0
            ].index
            rain_dur_hr = (
                weather_index.max()
                - weather_index.min()
                + weather_index.diff().dropna()[0]
            ) / np.timedelta64(1, "h")
            ax.set_title(f"{rain_dur_hr} hr rainfall")
            ax.set_xlabel("")
            ax.set_ylabel("")

            ax = axes[2, 0]
            ds_cmpnd_rainonly.where(ds_cmpnd_rainonly > 0).plot(x="x", y="y", ax=ax)
            ax.set_title("etype = compound, simtype = rainonly")
            ax.set_xlabel("")
            ax.set_ylabel("")
            ax.set_xticks([])
            ax.set_yticks([])
            ax = axes[2, 2]
            tseries_rain_cmpnd["waterlevel_m"].plot(ax=ax)
            tseries_rain_cmpnd["mm_per_hr"].plot(ax=ax, secondary_y=True)
            weather_index = tseries_rain_cmpnd[
                tseries_rain_cmpnd["mm_per_hr"] > 0
            ].index
            rain_dur_hr = (
                weather_index.max()
                - weather_index.min()
                + weather_index.diff().dropna()[0]
            ) / np.timedelta64(1, "h")
            ax.set_title(f"{rain_dur_hr} hr rainfall")
            ax.set_xlabel("")
            ax.set_ylabel("")

            # subtracting ds rain event, rain only sims
            ax = axes[0, 1]
            ds = ds_rain_cmpnd - ds_rain_rainonly
            ds.where(ds != 0).plot(x="x", y="y", ax=ax)
            ax.set_title("left minus (etype = rain, simtype = rainonly)")
            ax.set_xlabel("")
            ax.set_ylabel("")
            ax.set_xticks([])
            ax.set_yticks([])
            if (ds.to_dataframe()["max_wlevel_m"] == 0).all():
                ax.annotate(
                    "no differences",
                    xy=(0.25, 0.5),
                    xycoords="axes fraction",
                    fontsize=20,
                    color="k",
                )

            ax = axes[1, 1]
            ds = ds_rain_rainonly - ds_rain_rainonly
            ds.where(ds != 0).plot(x="x", y="y", ax=ax)
            ax.set_title("left minus (etype = rain, simtype = rainonly)")
            ax.set_xlabel("")
            ax.set_ylabel("")
            ax.set_xticks([])
            ax.set_yticks([])
            if (ds.to_dataframe()["max_wlevel_m"] == 0).all():
                ax.annotate(
                    "no differences\n(expected)",
                    xy=(0.25, 0.5),
                    xycoords="axes fraction",
                    fontsize=20,
                    color="k",
                )

            ax = axes[2, 1]
            ds = ds_cmpnd_rainonly - ds_rain_rainonly
            ds.where(ds != 0).plot(x="x", y="y", ax=ax)
            ax.set_title("left minus (etype = rain, simtype = rainonly)")
            ax.set_xlabel("")
            ax.set_ylabel("")
            ax.set_xticks([])
            ax.set_yticks([])
            if (ds.to_dataframe()["max_wlevel_m"] == 0).all():
                ax.annotate(
                    "no differences",
                    xy=(0.25, 0.5),
                    xycoords="axes fraction",
                    fontsize=20,
                    color="k",
                )
                plt.clf()
                continue
            else:
                df_diffs = ds.to_dataframe()
                # df_diffs = df_diffs[df_diffs["max_wlevel_m"] != 0]
                df_diffs = df_diffs[
                    ~np.isclose(df_diffs["max_wlevel_m"], 0, atol=0.01, rtol=0)
                ]
                # df_diffs[~np.isclose(df_diffs["max_wlevel_m"], 0, atol=0.01, rtol=0)][
                #     "max_wlevel_m"
                # ].plot.hist()

max_dsgn_wlevel = ds_triton_dsgn.max_wlevel_m.sel(
    data_source="dsgn", simtype="compound", model="tritonswmm"
)

ds_sim_flood_probs = return_ds_sim_flood_probs()

ds_multivar_return_periods_og = xr.open_dataset(
    F_SIM_MULTIVAR_RETURN_PERIODS, engine="zarr"
).chunk("auto")


ds_sim_flood_probs_bs_event_ids = retrieve_ssfha_bootstrapped_CIs()

if "contributing_event_id" not in ds_sim_flood_probs_bs_event_ids.data_vars:
    ds_CI_event_ids = return_event_ids_for_each_ssfha_quantile()
    ds_sim_flood_probs_bs_event_ids = xr.merge(
        [ds_sim_flood_probs_bs_event_ids, ds_CI_event_ids]
    )


# computing MC-based flood return periods
# multivar AND
rewrite = False
if Path(FPATH_MC_DESIGN_FLOODS_MULTIVAR_AND).exists():
    ds_mcds_return_pds_multivar_and = xr.open_dataset(
        FPATH_MC_DESIGN_FLOODS_MULTIVAR_AND
    )
    written_on = ds_mcds_return_pds_multivar_and.attrs["date_written"]
    if prompt_for_rerun:
        response = input(
            f"type 'yes' to re-write netcdf written on {written_on.split(" ")[0]} for flood depths of targeted return periods"
        )
        if response.lower() == "yes":
            rewrite = True
else:
    rewrite = True
if overwrite_outputs:
    rewrite = True
if rewrite:
    return_periods = ds_triton_dsgn.year.to_series().to_list()
    write_netcdf_of_mcds_return_period_floods(
        ds_sim_flood_probs,
        FORMULATION_FOR_MC_DSGN_STRM_SEL_MULTIVAR_AND,
        EVENT_STAT_FOR_MC_DSGN_STRM_SEL_MULTIVAR_AND,
        return_periods,
        FPATH_MC_DESIGN_FLOODS_MULTIVAR_AND,
    )
else:
    print(
        f"loading ds_mcds_return_pds_multivar_and from {FPATH_MC_DESIGN_FLOODS_MULTIVAR_AND}"
    )
    print("############")

ds_mcds_return_pds_multivar_and = xr.open_dataset(FPATH_MC_DESIGN_FLOODS_MULTIVAR_AND)

#  multivar OR
rewrite = False
if Path(FPATH_MC_DESIGN_FLOODS_MULTIVAR_OR).exists():
    ds_mcds_return_pds_multivar_or = xr.open_dataset(FPATH_MC_DESIGN_FLOODS_MULTIVAR_OR)
    written_on = ds_mcds_return_pds_multivar_or.attrs["date_written"]
    if prompt_for_rerun:
        response = input(
            f"type 'yes' to re-write netcdf written on {written_on.split(" ")[0]} for flood depths of targeted return periods"
        )
        if response.lower() == "yes":
            rewrite = True
else:
    rewrite = True
if overwrite_outputs:
    rewrite = True
if rewrite:
    return_periods = ds_triton_dsgn.year.to_series().to_list()
    write_netcdf_of_mcds_return_period_floods(
        ds_sim_flood_probs,
        FORMULATION_FOR_MC_DSGN_STRM_SEL_MULTIVAR_OR,
        EVENT_STAT_FOR_MC_DSGN_STRM_SEL_MULTIVAR_OR,
        return_periods,
        FPATH_MC_DESIGN_FLOODS_MULTIVAR_OR,
    )
else:
    print(
        f"loading ds_mcds_return_pds_multivar_or from {FPATH_MC_DESIGN_FLOODS_MULTIVAR_OR}"
    )
    print("############")

ds_mcds_return_pds_multivar_or = xr.open_dataset(FPATH_MC_DESIGN_FLOODS_MULTIVAR_OR)

# univar
rewrite = False
if Path(FPATH_MC_DESIGN_FLOODS_UNIVAR).exists():
    ds_mcds_return_pds_univar = xr.open_dataset(FPATH_MC_DESIGN_FLOODS_UNIVAR)
    written_on = ds_mcds_return_pds_univar.attrs["date_written"]
    if prompt_for_rerun:
        response = input(
            f"type 'yes' to re-write netcdf written on {written_on.split(" ")[0]} for flood depths of targeted return periods"
        )
        if response.lower() == "yes":
            rewrite = True
else:
    rewrite = True
if overwrite_outputs:
    rewrite = True
if rewrite:
    return_periods = ds_triton_dsgn.year.to_series().to_list()
    write_netcdf_of_mcds_return_period_floods(
        ds_sim_flood_probs,
        FORMULATION_FOR_MC_DSGN_STRM_SEL_UNIVAR,
        EVENT_STAT_FOR_MC_DSGN_STRM_SEL_UNIVAR,
        return_periods,
        FPATH_MC_DESIGN_FLOODS_UNIVAR,
    )
else:
    print(f"loading ds_mcds_return_pds_univar from {FPATH_MC_DESIGN_FLOODS_UNIVAR}")
    print("############")

ds_mcds_return_pds_univar = xr.open_dataset(FPATH_MC_DESIGN_FLOODS_UNIVAR)

#   computing ensemble-based flood return periods
rewrite = False
if Path(FPATH_ENSEMBLE_DESIGN_FLOODS).exists():
    ds_ensemble_return_pds = xr.open_dataset(FPATH_ENSEMBLE_DESIGN_FLOODS)
    written_on = ds_ensemble_return_pds.attrs["date_written"]
    if prompt_for_rerun:
        response = input(
            f"type 'yes' to re-write netcdf written on {written_on.split(" ")[0]} for flood depths of targeted return periods"
        )
        if response.lower() == "yes":
            rewrite = True
else:
    rewrite = True
if overwrite_outputs:
    rewrite = True
if rewrite:
    return_periods = ds_triton_dsgn.year.to_series().to_list()
    write_netcdf_of_ensemble_based_return_period_floods(
        ds_sim_flood_probs, return_periods
    )
else:
    print(f"loading ds_ensemble_return_pds from {FPATH_ENSEMBLE_DESIGN_FLOODS}")
    print("############")

ds_ensemble_return_pds = xr.open_dataset(FPATH_ENSEMBLE_DESIGN_FLOODS)


#  comparing ensemble to design storms
# params for plotting single locations
# plt.rcParams["text.usetex"] = True
loc_idx = -1
quants_to_compare = np.linspace(0, 1, 21)
lst_coords_analyzed = []
# clear previous location plots
# for f in glob(
#     f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/fld_crvs_1loc/*.png"
# ):
#     os.remove(f)

# comparing ensemble to design storms
#  plotting
dsgn_rain_dur = TARGET_DESIGN_STORM_DURATION_HRS_FOR_COMPARISON
lst_return_pds_to_analyze = None  # [2, 100]
threshold_for_plotting = MIN_THRESH_FLDING  # equal to or less than will be na
#%% loading and resampling FEMA flood depths
import rioxarray as rxr
import xarray as xr

def spatial_resampling(xds_to_resample, xds_target, missingfillval=-9999):
    import xarray as xr
    from rasterio.enums import Resampling

    # resample
    ## https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray.raster_dataset.RasterDataset.reproject_match
    ## (https://rasterio.readthedocs.io/en/stable/api/rasterio.enums.html#rasterio.enums.Resampling)
    xds_to_resampled = xds_to_resample.rio.reproject_match(  # type: ignore
        xds_target, resampling=Resampling.average
    )
    # fill missing values with prespecified val (this should just corresponds to areas where one dataset has pieces outside the other)
    xds_to_resampled = xr.where(
        xds_to_resampled >= 3.403e37, x=missingfillval, y=xds_to_resampled
    )
    return xds_to_resampled

ds_sim_flood_probs = ds_sim_flood_probs.rio.write_crs(rds_fema.rio.crs)

rds_fema = xr.open_dataset(F_RASTER_FEMA_100YR_DEPTHS)
rds_fema_resampled = spatial_resampling(rds_fema, ds_sim_flood_probs)


# %% plotting rain statistic vs. water level return periods

df_event_return_periods = (
    retrieve_event_statistic_return_periods_indexed_by_event_number()
)

import matplotlib.pyplot as plt

# arguments
ds_ensemble_return_pds
event_set = "event_numbers_with_geq_0.03m_flooding"


lst_event_stats = [
    "max_24hr_0min_mm_return_pd_yrs",
    "max_2hr_0min_mm_return_pd_yrs",
    # "max_1hr_0min_mm_return_pd_yrs",
    "1hr,w (AND)",
    "24hr,w (OR)",
]

if len(lst_event_stats) == 3:  # matches dimensions below
    fig_width = 6.1
    fig_height = 6
else:
    height_to_width = 5.1 / 6.72
    fig_width = 7
    fig_height = fig_width * height_to_width

figsize = (fig_width, fig_height)

fig, axes = plt.subplots(
    nrows=len(LST_RTRNS),
    ncols=len(lst_event_stats),
    figsize=figsize,
    sharex=True,
    sharey=True,
    dpi=300,
    constrained_layout=True,
)
from matplotlib import patheffects

ds_ssfha_rtrn_pds = ds_sim_flood_probs_bs_event_ids
# ds_ssfha_rtrn_pds = ds_ensemble_return_pds

#  maps of event statistic return periods
ax_id = -1
for idx_rtrn, return_period in enumerate(LST_RTRNS):
    for idx_x, event_stat in enumerate(lst_event_stats):
        ax_id += 1
        ax = axes[idx_rtrn, idx_x]
        plt_map, ticks, color_target_rtrn = (
            plot_event_statistic_return_period_maps_for_target_return_period_and_minimum_flood_depth(
                ax,
                df_event_return_periods,
                ds_ssfha_rtrn_pds,
                return_period,
                event_stat,
                anchor_vals=np.asarray([1, 2, 10, 50, 100, 250]),
                ticks=[1, 2, 10, 50, 100, 200],
                min_fld_thrsh=0.03,
                quants=[0.1, 0.5, 0.9],
                cmap_name="Spectral_r",
                # cmap_name="rainbow",
                # cmap_name="viridis",
                # cmap_name="plasma",
                # cmap_name="cividis",
            )
        )
        add_subplot_id(ax=ax, ax_id=ax_id, x=0.02, y=0.98)
        if idx_x == 0:
            ax.set_ylabel(
                f"{return_period} year",
                weight="heavy",
                color=color_target_rtrn,
                path_effects=[patheffects.withStroke(linewidth=1.25, foreground="k")],
            )
        if idx_rtrn == 0:
            if "OR" in event_stat:
                title = title = tidy_hydro_varnames_for_plots(event_stat, "OR")
                title = title.replace("OR", "OR\n")
            else:
                title = tidy_hydro_varnames_for_plots(event_stat, "AND")
                if "AND" in title:
                    title = title.replace("AND", "AND\n")
            ax.set_title(
                title,
            )

# Add a horizontal colorbar below the plots, centered horizontally
colorbar_width = 0.6  # Width of the colorbar (fraction of figure width)
cbar_left = (1 - colorbar_width) / 2  # Calculate left position to center it


# if n_rows > 1:
cbar_ax = fig.add_axes(
    [cbar_left, -0.05, colorbar_width, 0.03]
)  # [left, bottom, width, height]

cbar = fig.colorbar(plt_map, cax=cbar_ax, extend="both", orientation="horizontal")
cbar.set_ticks(ticks)  # Remove the last bin as it represents 'over'
cbar.ax.set_xticklabels([str(t) for t in ticks])

cbar_ax.set_xlabel("Event Return Period (yr)", fontsize=10)

# fig.tight_layout()


fname_save_fig = f"{DIR_PLOTS_FLOOD_VS_EVENT_PROB}maps_of_event_statistic_return_period_across_hazard_levels.png"
plt.savefig(fname_save_fig, bbox_inches="tight")

# %% scatterplot
# y_axis = "max_waterlevel_m_return_pd_yrs"
# for idx_rtrn, return_period in enumerate(LST_RTRNS):
#     for idx_x, x_axis in enumerate(lst_xs):
#         ax = axes[idx_rtrn, idx_x]

#         s_contributing_events = plot_event_statistic_return_period_scatterplots_for_target_return_period_and_minimum_flood_depth(
#             ax=ax,
#             df_event_return_periods=df_event_return_periods,
#             ds_ensemble_return_pds=ds_ensemble_return_pds,
#             return_period=return_period,
#             event_set=event_set,
#             ensemble_type=ensemble_type,
#             x_axis=x_axis,
#             y_axis=y_axis,
#         )

#         if idx_x == 0:
#             ax.set_ylabel(
#                 f"{return_period} year ({len(s_contributing_events):,} events)\n{y_axis}"
#             )
#         if idx_rtrn == (len(LST_RTRNS) - 1):
#             ax.set_xlabel(x_axis)
# if idx_rtrn == 0:
#     ax.set_title(f"{len(s_contributing_events):,}")


# %%
lst_df_diffs = []

dict_titles_diffs = {}
dict_titles = {}
dict_diffs = {}
dict_floods = {}

for target_return_pd in LST_RTRNS:

    if lst_return_pds_to_analyze is not None:
        if target_return_pd not in lst_return_pds_to_analyze:
            continue
    # subset x-y locations with nearest return period
    # if da_sim_flood_probs_bs is None:
    ds_baseline = ds_ensemble_return_pds.sel(
        ensemble_type="compound", year=target_return_pd
    )

    da_sim_flood_probs_bs = ds_sim_flood_probs_bs_event_ids["max_wlevel_m"]
    # da_baseline = ds_baseline["max_wlevel_m"]
    # else:
    da_sim_flood_probs_bs_rtrn = None
    if da_sim_flood_probs_bs is not None:
        da_sim_flood_probs_bs_rtrn = da_sim_flood_probs_bs.sel(
            return_pd_yrs=target_return_pd
        )

    ds_alt_ensemble = ds_ensemble_return_pds.drop_sel(ensemble_type="compound").sel(
        year=target_return_pd
    )

    ds_mcds_univar = ds_mcds_return_pds_univar.sel(year=target_return_pd)
    ds_mcds_multivar_and = ds_mcds_return_pds_multivar_and.sel(year=target_return_pd)
    ds_mcds_multivar_or = ds_mcds_return_pds_multivar_or.sel(year=target_return_pd)

    lst_ds_mcds = [ds_mcds_univar, ds_mcds_multivar_and, ds_mcds_multivar_or]

    grid_size = return_ds_gridsize(ds_baseline)

    # threshold_m = NUISANCE_THRESHOLD  # ds_baseline.attrs["flood_threshold_for_filtering_n_unique_events_m"]

    # ds_baseline["contributing_event_id"].where(ds_baseline["max_wlevel_m"] >= NUISANCE_THRESHOLD)

    # initialize lists of datasets and titles to plot

    (
        __,
        lst_ds_rtrn,
        lst_titles,
        lst_titles_diff,
        lst_ds_rtrn_diff,
        lst_df_flooded_volumes,
        df_flooded_areas,
    ) = analyze_baseline_flooded_area_vs_design_storm_flooded_areas(
        ds_baseline,
        da_sim_flood_probs_bs_rtrn,
        ds_alt_ensemble,
        lst_ds_mcds,
        ds_triton_dsgn,
        ds_dsgn_tseries,
        dsgn_rain_dur,
        target_return_pd,
    )
    dict_titles[target_return_pd] = lst_titles
    dict_floods[target_return_pd] = lst_ds_rtrn

    dict_titles_diffs[target_return_pd] = lst_titles_diff
    dict_diffs[target_return_pd] = lst_ds_rtrn_diff

    # %% skipping plotting for now
    sys.exit("skipping these plots for now")

    # flood volumes by appraoch; plot would need work if I wanted to use;
    plot_flooded_areas_baseline_vs_alt(df_flooded_areas, target_return_pd, clf=clf)

    # flood maps across all methods
    fig_title = f"{target_return_pd}-year Flood Depth Probability Maps"
    lab_cbar = "Water Level (m)"

    cbar_bins = (
        LST_KEY_FLOOD_THRESHOLDS  # nuisance flood depths up to 0.1; after are dangerous
    )
    cbar_tick_lables = [str(lab) for lab in cbar_bins]
    cmap_name = "YlGnBu"
    datasets = lst_ds_rtrn
    titles = lst_titles
    cbar_colors = None
    set_under = "white"
    fname_save_fig = f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/flood_prob_map_{target_return_pd}yr_ensemble_vs_dsgn_strms.png"
    Path(fname_save_fig).unlink(missing_ok=True)
    shapefile_path = F_WSHED_SHP
    plot_triton_results(
        datasets=datasets,
        titles=titles,
        lab_cbar=lab_cbar,
        cmap_name=cmap_name,
        fig_title=fig_title,
        cbar_bins=cbar_bins,
        cbar_tick_lables=cbar_tick_lables,
        fname_save_fig=fname_save_fig,
        set_under=set_under,
        cbar_colors=cbar_colors,
        shapefile_path=shapefile_path,
        n_cols=4,
        clf=clf,
    )

    # baseline only (TRITON-SWMM compound ensemble)
    fname_save_fig = f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/flood_prob_map_{target_return_pd}yr_ensemble.png"
    Path(fname_save_fig).unlink(missing_ok=True)
    datasets = [
        da_baseline.where(da_baseline > MIN_THRESH_FLDING)
    ]  # when plotting this by itself, only use where flooding exceeds the threshold
    titles = [""]
    fig_title = None
    plot_triton_results(
        datasets=datasets,
        titles=titles,
        lab_cbar=lab_cbar,
        cmap_name=cmap_name,
        fig_title=fig_title,
        cbar_bins=cbar_bins,
        cbar_tick_lables=cbar_tick_lables,
        fname_save_fig=fname_save_fig,
        set_under=set_under,
        cbar_colors=cbar_colors,
        shapefile_path=shapefile_path,
        n_cols=1,
        clf=clf,
    )
    datasets = lst_ds_rtrn_diff
    titles = lst_titles[1:]
    lst_s_diffs_rtrn = plot_histogram_of_differences_in_flood_depths_vs_baseline(
        datasets, titles, target_return_pd, clf
    )

    if plot_examples_of_flood_prob_curves:
        plot_ensemble_vs_alternatives_probability_depth_curves_at_individual_gridcells(
            lst_s_diffs_rtrn,
            target_return_pd,
            lst_df_diffs,
            lst_ds_rtrn_diff,
            quants_to_compare,
            ds_sim_flood_probs,
            max_dsgn_wlevel,
            lst_ds_rtrn,
            titles,
            shapefile_path,
            ds_sim_flood_probs_bs,
            clf,
        )

# %% plotting flood maps
# if Path(f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/").exists():
#     shutil.rmtree(Path(f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/"))
#     time.sleep(0.01)

Path(f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/").mkdir(exist_ok=True)
dict_titles[target_return_pd]
dict_floods[target_return_pd]

idx_ss_fha = 1, 4
# idx_design = 0, 3
# idx_ss = 3, 6
# idx_mcds_univar = 6, 9
# idx_mcds_multivar = 9, 12

dict_indices = {
    "SS": idx_ss_fha,
    # "SS": idx_ss,
    # "MCDS-Univar": idx_mcds_univar,
    # "MCDS-Multivar": idx_mcds_multivar,
}

# check
idx = idx_ss_fha
dict_titles[2][idx[0] : idx[1]]

rtrns = [2, 10, 100]

clf = False

for key in dict_indices.keys():
    idx = dict_indices[key]
    titles = []
    datasets = []
    master_row_titles = []
    for rtn_pd in dict_titles.keys():
        master_col_titles = []
        if rtn_pd not in rtrns:
            continue
        for title in dict_titles[rtn_pd][idx[0] : idx[1]]:
            if key == "SS":
                master_col_titles.append(title)
            else:
                sys.exit("undefined")
            title += f" ({rtn_pd} yr)"
            titles.append(title)
        master_row_titles.append(
            f"{rtn_pd} year"  # ({int(title.split("(")[1].split(" ")[0]):,} events)"
        )
        for ds in dict_floods[rtn_pd][idx[0] : idx[1]]:
            datasets.append(ds)

    n_cols = max(idx_ss_fha) - min(idx_ss_fha)
    fig_title = f"{key}"
    cmap_name = "coolwarm_r"
    # cbar_bins = np.linspace(
    #     -0.1, 0.1, 10
    # )  # nuisance flood depths up to 0.1; after are dangerous
    cbar_bins = [0] + LST_FLOOD_DEPTH_BIN_EDGES
    cbar_tick_lables = [f"{lab:.2f}" for lab in cbar_bins]
    # https://colorbrewer2.org/?type=diverging&scheme=RdYlBu&n=9
    cbar_colors = [
        "white",
        "#ffffcc",
        "#a1dab4",
        "#41b6c4",
        "#2c7fb8",  # 54278f
    ]
    lab_cbar = "Depth (m)"
    fig_title = None  # "Alternative minus baseline (ensemble-based flood depths)"
    fname_save_fig = f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/flood_maps_{key}_by_quant.png"
    Path(fname_save_fig).unlink(missing_ok=True)
    shapefile_path = F_WSHED_SHP
    set_under = None  # "pink"
    set_over = "#253494"
    figsize = (7, 6)

    plot_cbar = True

    # titles = master_col_titles
    # master_col_titles = None
    # master_row_titles = None
    # sys.exit("work")
    plot_triton_results(
        datasets=datasets,
        titles=titles,
        lab_cbar=lab_cbar,
        cmap_name=cmap_name,
        fig_title=fig_title,
        cbar_bins=cbar_bins,
        cbar_tick_lables=cbar_tick_lables,
        master_col_titles=master_col_titles,
        master_row_titles=master_row_titles,
        fname_save_fig=fname_save_fig,
        set_over=set_over,
        set_under=set_under,
        cbar_colors=cbar_colors,
        shapefile_path=shapefile_path,
        n_cols=n_cols,
        clf=clf,
        figsize=figsize,
    )

# %% alternative flood hazard maps showing CI differently
all_datasets = []
flood_hazard_datasets = []
CI_hazard_datasets = []
all_titles = []
flood_hazard_titles = []
CI_titles = []
master_col_titles = None
master_row_titles = []

quants = da_sim_flood_probs_bs["quantile"].to_series()

da_median_flood = da_sim_flood_probs_bs.sel(quantile=0.5)
da_flood_ci_magnitude = da_sim_flood_probs_bs.sel(
    quantile=quants.max()
) - da_sim_flood_probs_bs.sel(quantile=quants.min())

quant_range = quants.max() - quants.min()

for rtrn in da_sim_flood_probs_bs.return_pd_yrs:
    master_row_titles.append(f"{int(rtrn)} year")
    da_most_flood = da_sim_flood_probs_bs.sel(return_pd_yrs=rtrn, quantile=quants.max())
    max_where_flooded = da_most_flood > 0

    da_median_flood_rtrn = da_median_flood.sel(return_pd_yrs=rtrn).where(
        max_where_flooded
    )
    all_datasets.append(da_median_flood_rtrn)
    flood_hazard_datasets.append(da_median_flood_rtrn)
    title = f"{int(rtrn)}-year q={0.5}"
    all_titles.append(title)
    flood_hazard_titles.append(title)

    da_flood_ci_magnitude_rtrn = da_flood_ci_magnitude.sel(return_pd_yrs=rtrn).where(
        max_where_flooded
    )
    all_datasets.append(da_flood_ci_magnitude_rtrn)
    CI_hazard_datasets.append(da_flood_ci_magnitude_rtrn)
    title = f"{int(rtrn)}-year {quant_range*100:.0f}% CI"
    all_titles.append(title)
    CI_titles.append(title)


n_cols = 2
fig_title = None
cmap_name = "YlGnBu"
# cbar_bins = np.linspace(
#     -0.1, 0.1, 10
# )  # nuisance flood depths up to 0.1; after are dangerous
cbar_bins_for_labeling = [0.01, 0.05, 0.1, 0.5, 1]  # [0] + LST_FLOOD_DEPTH_BIN_EDGES
cbar_tick_lables = [f"{lab:.2f}" for lab in cbar_bins_for_labeling]

cbar_bins = list(np.linspace(start=0.01, stop=0.1, num=10)) + list(
    np.linspace(start=0.2, stop=1, num=9)
)

lab_cbar = "Depth (m)"
fig_title = None  # "Alternative minus baseline (ensemble-based flood depths)"
fname_save_fig = (
    f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/flood_maps_{key}.png"
)
Path(fname_save_fig).unlink(missing_ok=True)
shapefile_path = F_WSHED_SHP
set_under = "white"  # "pink"
set_over = None  # "#253494"
figsize = (3.5, 5)

plot_cbar = True

titles = all_titles
datasets = all_datasets

master_col_titles = ["SS, q=0.5", "90% CI Range"]
master_row_titles

plot_triton_results(
    datasets=datasets,
    titles=titles,
    lab_cbar=lab_cbar,
    cmap_name=cmap_name,
    fig_title=fig_title,
    cbar_bins=cbar_bins,
    cbar_bins_for_labeling=cbar_bins_for_labeling,
    cbar_tick_lables=cbar_tick_lables,
    master_col_titles=master_col_titles,
    master_row_titles=master_row_titles,
    fname_save_fig=fname_save_fig,
    set_over=set_over,
    set_under=set_under,
    cbar_colors=None,
    shapefile_path=shapefile_path,
    n_cols=n_cols,
    clf=clf,
    figsize=figsize,
)
#%% creating one-off fema vs. SS FHA flood map
ss_fha_100yr = datasets[4]
da_fema = rds_fema_resampled.rename(dict(band_data = "max_wlevel_m"))['max_wlevel_m']
diff = da_fema.fillna(0) - ss_fha_100yr

cmap_name = "bwr_r"

cbar_bins_for_labeling = [0, 0.05, 0.1, 0.5, 1]
cbar_bins_for_labeling = list(
    np.sort(np.asarray(cbar_bins_for_labeling) * -1)
) + list(np.sort(np.asarray(cbar_bins_for_labeling)))

cbar_bins_for_labeling = pd.Series(cbar_bins_for_labeling).unique()
cbar_tick_lables = [f"{lab:.2f}" for lab in cbar_bins_for_labeling]

cbar_bins = list(np.linspace(start=0.01, stop=0.1, num=10)) + list(
    np.linspace(start=0.2, stop=1, num=9)
)

cbar_bins = (
    list(np.sort(np.asarray(cbar_bins) * -1))
    + [0]
    + list(np.sort(np.asarray(cbar_bins)))
)

lab_cbar = "FEMA minus SS (m)"

fig_title = None

plot_triton_results(
    datasets=[diff],
    titles=["FEMA Comparison"],
    lab_cbar=lab_cbar,
    cmap_name=cmap_name,
    fig_title=fig_title,
    cbar_bins=cbar_bins,
    cbar_tick_lables=cbar_tick_lables,
    cbar_bins_for_labeling=cbar_bins_for_labeling,
    master_col_titles=None,
    master_row_titles=None,
    fname_save_fig=None,
    set_under=None,
    cbar_colors=None,  # cbar_colors,
    shapefile_path=shapefile_path,
    n_cols=n_cols,
    clf=clf,
    figsize=figsize,
    add_subplot_ids=False
)


cmap_name = "YlGnBu"
# cbar_bins = np.linspace(
#     -0.1, 0.1, 10
# )  # nuisance flood depths up to 0.1; after are dangerous
cbar_bins_for_labeling = [0.01, 0.05, 0.1, 0.5, 1]  # [0] + LST_FLOOD_DEPTH_BIN_EDGES
cbar_tick_lables = [f"{lab:.2f}" for lab in cbar_bins_for_labeling]

cbar_bins = list(np.linspace(start=0.01, stop=0.1, num=10)) + list(
    np.linspace(start=0.2, stop=1, num=9)
)

lab_cbar = "Depth (m)"

set_under = "white"  # "pink"
set_over = None  # "#253494"

# plot FEMA flood map
plot_triton_results(
    datasets=[da_fema],
    titles=["FEMA"],
    lab_cbar=lab_cbar,
    cmap_name=cmap_name,
    fig_title=fig_title,
    cbar_bins=cbar_bins,
    cbar_tick_lables=cbar_tick_lables,
    cbar_bins_for_labeling=cbar_bins_for_labeling,
    master_col_titles=None,
    master_row_titles=None,
    fname_save_fig=None,
    set_under=set_under,
    cbar_colors=None,  # cbar_colors,
    shapefile_path=shapefile_path,
    n_cols=n_cols,
    clf=clf,
    figsize=figsize,
    add_subplot_ids=False
)

plot_triton_results(
    datasets=[ss_fha_100yr],
    titles=["SS 100-year"],
    lab_cbar=lab_cbar,
    cmap_name=cmap_name,
    fig_title=fig_title,
    cbar_bins=cbar_bins,
    cbar_tick_lables=cbar_tick_lables,
    cbar_bins_for_labeling=cbar_bins_for_labeling,
    master_col_titles=None,
    master_row_titles=None,
    fname_save_fig=None,
    set_under=set_under,
    cbar_colors=None,  # cbar_colors,
    shapefile_path=shapefile_path,
    n_cols=n_cols,
    clf=clf,
    figsize=figsize,
    add_subplot_ids=False
)
# %%  plotting differences
idx_design = 0, 3
idx_ss = idx_design[1], idx_design[1] + 4
idx_mcds_univar = idx_ss[1], idx_ss[1] + 3
idx_mcds_multivar_and = idx_mcds_univar[1], idx_mcds_univar[1] + 3
idx_mcds_multivar_or = idx_mcds_multivar_and[1], idx_mcds_multivar_and[1] + 3

dict_indices = {
    "BDS": idx_design,
    "SS": idx_ss,
    "MCDS-Univar": idx_mcds_univar,
    "MCDS-Multivar (AND)": idx_mcds_multivar_and,
    "MCDS-Multivar (OR)": idx_mcds_multivar_or,
}

# check
idx = idx_ss
dict_titles_diffs[2][idx[0] : idx[1]]

clf = False

for key in dict_indices.keys():
    idx = dict_indices[key]
    titles = []
    datasets = []
    master_row_titles = []
    for rtn_pd in dict_titles_diffs.keys():
        master_col_titles = []
        if rtn_pd not in LST_RTRNS:
            continue
        for title in dict_titles_diffs[rtn_pd][idx[0] : idx[1]]:
            title += f" ({rtn_pd} yr)"
            titles.append(title)
            if key == "BDS":
                if (
                    "design rain event" in title
                    and "year boundary water levels" in title
                ):
                    master_col_titles.append("BDS")
                elif "median boundary water levels" in title:
                    master_col_titles.append("RO-BDS")
                elif "no rainfall" in title:
                    master_col_titles.append("SO-BDS")
                elif "max of" in title:
                    master_col_titles.append("Max of SS/RO-BDS")
                else:
                    print(title)
                    sys.exit("undefined")
            if key == "SS":
                if "2D_compound" in title:
                    master_col_titles.append("2D-SS")
                elif "rain_only" in title:
                    master_col_titles.append("RO-SS")
                elif "surge_only" in title:
                    master_col_titles.append("SO-SS")
                elif "1driver_max" in title:
                    master_col_titles.append("Max of SS/RO-SS")
                else:
                    print(title)
                    sys.exit("undefined")
            elif key == "MCDS-Univar":
                quant = title.split("quantile = ")[-1].split(")")[0]
                master_col_titles.append(f"MCDS-U, q = {quant}")
            elif "MCDS-Multivar" in key:
                if "AND" in key:
                    form = "AND"
                elif "OR" in key:
                    form = "OR"
                quant = title.split("quantile = ")[-1].split(")")[0]
                master_col_titles.append(f"MCDS-{form}, q = {quant}")
        for ds in dict_diffs[rtn_pd][idx[0] : idx[1]]:
            datasets.append(ds)
        master_row_titles.append(f"{rtn_pd} year")
    n_cols = len(dict_titles_diffs[rtn_pd][idx[0] : idx[1]])
    fig_title = f"{key}"
    # cmap_name = "seismic_r"
    cmap_name = "bwr_r"
    # cbar_bins = np.linspace(
    #     -0.1, 0.1, 10
    # )  # nuisance flood depths up to 0.1; after are dangerous

    cbar_bins_for_labeling = [0, 0.05, 0.1, 0.5, 1]
    cbar_bins_for_labeling = list(
        np.sort(np.asarray(cbar_bins_for_labeling) * -1)
    ) + list(np.sort(np.asarray(cbar_bins_for_labeling)))

    cbar_bins_for_labeling = pd.Series(cbar_bins_for_labeling).unique()
    cbar_tick_lables = [f"{lab:.2f}" for lab in cbar_bins_for_labeling]

    cbar_bins = list(np.linspace(start=0.01, stop=0.1, num=10)) + list(
        np.linspace(start=0.2, stop=1, num=9)
    )

    cbar_bins = (
        list(np.sort(np.asarray(cbar_bins) * -1))
        + [0]
        + list(np.sort(np.asarray(cbar_bins)))
    )

    # cbar_bins = np.asarray(
    #     [-1.00, -0.30, -0.10, -0.03, -0.01, 0.01, 0.03, 0.10, 0.30, 1.00]
    # )
    # cbar_tick_lables = [f"{lab:.2f}" for lab in cbar_bins]
    # https://colorbrewer2.org/?type=diverging&scheme=RdYlBu&n=9
    # cbar_colors = [
    #     "#d73027",
    #     "#f46d43",
    #     "#fdae61",
    #     "#fee090",
    #     "white",
    #     "#e0f3f8",
    #     "#abd9e9",
    #     "#74add1",
    #     "#4575b4",
    # ]
    lab_cbar = "Alt. minus SS (m)"
    fig_title = None  # "Alternative minus baseline (ensemble-based flood depths)"
    fname_save_fig = f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/flood_prob_map_diffs_{key}.png"
    Path(fname_save_fig).unlink(missing_ok=True)
    shapefile_path = F_WSHED_SHP
    set_under = None

    if n_cols == 3:
        fig_width = 6.2
        fig_height = 6
    else:
        fig_width = 6.72
        fig_height = 4.9
    figsize = (fig_width, fig_height)

    plot_triton_results(
        datasets=datasets,
        titles=titles,
        lab_cbar=lab_cbar,
        cmap_name=cmap_name,
        fig_title=fig_title,
        cbar_bins=cbar_bins,
        cbar_tick_lables=cbar_tick_lables,
        cbar_bins_for_labeling=cbar_bins_for_labeling,
        master_col_titles=master_col_titles,
        master_row_titles=master_row_titles,
        fname_save_fig=fname_save_fig,
        set_under=set_under,
        cbar_colors=None,  # cbar_colors,
        shapefile_path=shapefile_path,
        n_cols=n_cols,
        clf=clf,
        figsize=figsize,
    )
    # sys.exit("work")
# %%
#  plot flood volume bar plots
print(
    "the plots below this point are valid but not currently targeted for including in publications"
)
print("these are the plots comparing peak flood volume across the system")
sys.exit(0)

df_flooded_volumes = pd.concat(lst_df_flooded_volumes, axis=0)
col_order = ["ensemble-based", "compound", "rain-only", "water level-only"]

df_flooded_volumes_median = (
    df_flooded_volumes.groupby(["year", "simtype"])["flooded_volume"]
    .median()
    .unstack(level=-1)
    .loc[:, col_order]
)
df_flooded_volumes_min = (
    df_flooded_volumes.groupby(["year", "simtype"])["flooded_volume"]
    .min()
    .unstack(level=-1)
    .loc[:, col_order]
)
df_flooded_volumes_max = (
    df_flooded_volumes.groupby(["year", "simtype"])["flooded_volume"]
    .max()
    .unstack(level=-1)
    .loc[:, col_order]
)


colors = ["black", "#9467bd", "#17becf", "#ff7f0e"]
fig, ax = plt.subplots(dpi=300, figsize=(5.5, 3))
# df_flooded_areas = pd.concat(lst_flooded_areas_by_threshold, axis = 1) / (1000**2)

df_uncertainty = (
    (df_flooded_volumes_max - df_flooded_volumes_min)
    .astype(float)
    .replace(to_replace=0, value=np.nan)
)

df_flooded_volumes_median.plot.bar(yerr=df_uncertainty, ax=ax, color=colors, capsize=3)

err_linewidth = 0
err_capthick = 0.8
err_capsize = 3
# ax.errorbar(df_flooded_volumes_median.index, df_flooded_volumes_median,
#                 yerr=lst_y_err, fmt='', ecolor='black', capsize=err_capsize, capthick=err_capthick, linewidth=err_linewidth, zorder=1)
ax.legend(title="")
ax.set_xlabel("")
# ax.legend(custom_labels, title='', loc='best')
ax.set_ylabel("flooded volume (m$^3$)")
ax.set_xticklabels(
    [f"{i}-year" for i in df_flooded_volumes_median.index], rotation=45, ha="right"
)
fname_save_fig = f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/flood_prob_map_ensemble_vs_dsgn_strms_volumes.png"
Path(fname_save_fig).parent.mkdir(parents=True, exist_ok=True)
plt.savefig(fname_save_fig=fname_save_fig, bbox_inches="tight")
plt.clf()

#
# plot total differences (under and over estimates)
df_diffs = pd.concat(lst_df_diffs, ignore_index=True)
df_diffs = df_diffs.set_index(["index", "return_period"])


print(
    "Hard coded to assume that water level design storm estimates do not have uncertainty bounds. This is fine unless you know that ranges were simulated."
)
print("############")

lst_dfs_median = [df_diffs.loc[:, ["water level-only"]]]
lst_dfs_max = [df_diffs.loc[:, ["water level-only"]]]
lst_dfs_min = [df_diffs.loc[:, ["water level-only"]]]

modeling_ranges_for_design_storm_rainfall = False
for etype in ["compound", "rain-only"]:
    df_diffs_median = df_diffs.loc[:, etype].copy()
    df_diffs_median.name = etype
    lst_dfs_median.append(df_diffs_median)
    if len(df_diffs.loc[:, "compound"].shape) > 1:
        if df_diffs.loc[:, "compound"].shape[1] > 1:
            modeling_ranges_for_design_storms = True
            df_diffs_median = df_diffs.loc[:, etype].median(axis=1)
            df_diffs_max = df_diffs.loc[:, etype].max(axis=1)
            df_diffs_min = df_diffs.loc[:, etype].min(axis=1)
            df_diffs_max.name = etype
            df_diffs_min.name = etype
            lst_dfs_max.append(df_diffs_max)
            lst_dfs_min.append(df_diffs_min)

df_diffs_median = pd.concat(lst_dfs_median, axis=1)
df_diffs_median = df_diffs_median.reset_index()

if modeling_ranges_for_design_storms:
    df_diffs_max = pd.concat(lst_dfs_max, axis=1)
    df_diffs_min = pd.concat(lst_dfs_min, axis=1)

    df_diffs_max = df_diffs_max.reset_index()
    df_diffs_min = df_diffs_min.reset_index()

#
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


df_positive = (
    df_diffs_median[df_diffs_median["index"] == "overestimate"]
    .drop(columns=["index"])
    .set_index("return_period")
)
df_negative = (
    df_diffs_median[df_diffs_median["index"] == "underestimate"]
    .drop(columns=["index"])
    .set_index("return_period")
)

if modeling_ranges_for_design_storms:  # compute errorbars
    df_positive_max = (
        df_diffs_max[df_diffs_max["index"] == "overestimate"]
        .drop(columns=["index"])
        .set_index("return_period")
    )
    df_negative_max = (
        df_diffs_max[df_diffs_max["index"] == "underestimate"]
        .drop(columns=["index"])
        .set_index("return_period")
    )

    df_positive_min = (
        df_diffs_min[df_diffs_min["index"] == "overestimate"]
        .drop(columns=["index"])
        .set_index("return_period")
    )
    df_negative_min = (
        df_diffs_min[df_diffs_min["index"] == "underestimate"]
        .drop(columns=["index"])
        .set_index("return_period")
    )

    df_positive_error = (df_positive_max - df_positive_min).replace(0, np.nan)
    df_negative_error = (df_negative_max - df_negative_min).replace(0, np.nan)

index = df_positive.index
columns = df_positive.columns
# df_positive = pd.DataFrame(np.random.rand(4, 3) * 10, index=index, columns=columns)
# df_negative = -pd.DataFrame(np.random.rand(4, 3) * 10, index=index, columns=columns)

# Define colors and hatch patterns
colors = {"compound": "#9467bd", "rain-only": "#17becf", "water level-only": "#ff7f0e"}
positive_hatch = None  # No pattern for positive bars
negative_hatch = "//"  # Diagonal stripes for negative bars

# Plotting
fig, ax = plt.subplots(figsize=(8, 4.5), dpi=300)

bar_width = 0.2  # Width of each bar
x = np.arange(len(df_positive.index))  # X positions for groups

err_linewidth = 0
err_capthick = 1
err_capsize = 3
elinewidth = 1.5
# Plot each column
for i, column in enumerate(df_positive.columns):
    # Positive values
    bars_positive = ax.bar(
        x + i * bar_width,
        df_positive[column],
        width=bar_width,
        color=colors[column],
        hatch=positive_hatch,
        label=f"{column}",
    )
    if modeling_ranges_for_design_storms:  # positive errors
        ax.errorbar(
            x + i * bar_width,
            df_positive[column],
            yerr=df_positive_error[column],
            fmt="",
            ecolor="black",
            elinewidth=elinewidth,
            capsize=err_capsize,
            capthick=err_capthick,
            linewidth=err_linewidth,
            zorder=1,
        )

    # Negative values
    bars_negative = ax.bar(
        x + i * bar_width,
        df_negative[column],
        width=bar_width,
        color=colors[column],
        hatch=negative_hatch,
    )
    if modeling_ranges_for_design_storms:  # negative errors
        ax.errorbar(
            x + i * bar_width,
            df_negative[column],
            yerr=df_negative_error[column],
            fmt="",
            ecolor="black",
            elinewidth=elinewidth,
            capsize=err_capsize,
            capthick=err_capthick,
            linewidth=err_linewidth,
            zorder=1,
        )

    y_min, y_max = ax.get_ylim()  # Get the y-axis limits

    # Add labels for positive values
    for bar, value in zip(bars_positive, df_positive[column].round()):
        ax.text(
            (bar.get_x() + bar.get_width() / 2) * 1.004,
            bar.get_height() + 0.01 * (y_max - y_min),  # Slightly above the bar
            f"{int(value)}",
            ha="center",
            va="bottom",
            rotation=270,
        )
    # Add labels for negative values
    for bar, value in zip(bars_negative, df_negative[column].round()):
        ax.text(
            (bar.get_x() + bar.get_width() / 2) * 1.004,
            bar.get_height() - 0.003 * (y_max - y_min),  # Slightly below the bar
            f"{int(value)}",
            ha="left",
            va="top",
            rotation=270,
        )

x_lower = df_negative.min().min()
x_upper = df_positive.max().max()

range = x_upper - x_lower
expansion_adjuster_upper = 0.1
expansion_adjuster_lower = 0.2

ax.set_ylim(
    (
        x_lower - range * expansion_adjuster_lower,
        x_upper + range * expansion_adjuster_upper,
    )
)
# Formatting the plot
ax.axhline(0, color="black", linewidth=0.8)  # X-axis at 0
ax.set_xticks(x + bar_width * (len(df_positive.columns) - 1) / 2)
ax.set_xticklabels(df_positive.index)
ax.set_ylabel("design storm flood volume under- and over-estimation (m$^3$)")
ax.set_xlabel("")
ax.set_xticklabels([f"{i}-year" for i in df_positive.index], rotation=45, ha="right")
ax.set_title("")
ax.legend()
# fig.tight_layout()
fname_save_fig = f"{DIF_FFA_FLOOD_MAPPING}plots/ensemble_vs_dsgn_strms/flood_prob_map_ensemble_vs_dsgn_strms_volume_diffs.png"
Path(fname_save_fig).parent.mkdir(parents=True, exist_ok=True)
plt.savefig(fname_save_fig=fname_save_fig, bbox_inches="tight")
plt.clf()
